#
# Copyright (c) 2020 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

name: Release Che Devfile Registry

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'release version in format 7.y.z'
        required: true
  push:
    branches: 
      - 'release'
    paths:
      - 'VERSION'

jobs:
  release-build-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Clone source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          ref: release

      - name: Prepare
        id: prep
        run: |
          SHORT_SHA1=$(git rev-parse --short HEAD)
          echo ::set-output name=short_sha1::${SHORT_SHA1}
          VERSION=$(head -n 1 VERSION)
          echo ::set-output name=version::${VERSION}
          IMAGE=che-devfile-registry
          echo ::set-output name=image::${IMAGE}
          PLATFORMS=$(cat PLATFORMS)
          echo ::set-output name=platforms::${PLATFORMS}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1.1.2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Login to Quay.io
        uses: azure/docker-login@v1
        with:
          login-server: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Login to Docker Hub
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push patched base images and happy path image
        run: |
          export TAG=$(head -n 1 VERSION)
          /bin/bash arbitrary-users-patch/happy-path/build_happy_path_image.sh --push
          /bin/bash arbitrary-users-patch/build_images.sh --push
